ecole_back:
    resource: "@EcoleBackBundle/Resources/config/routing.yml"
    prefix:   /back

ecole_front:
    resource: "@EcoleFrontBundle/Resources/config/routing.yml"
    prefix:   /

ecole_fos_user:
    resource: "@EcoleUserBundle/Resources/config/routing.yml"
    prefix: /user

for_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

